## mysql
dataplatform.rh.db.conn.driver-class-name: com.mysql.cj.jdbc.Driver
# 10.0.4.12
dataplatform.rh.db.conn.jdbcUrl: jdbc:mysql://localhost:3306/resume_hunter?characterEncoding=utf8&useSSL=false
dataplatform.rh.db.conn.userName: root
dataplatform.rh.db.conn.password: 123456
dataplatform.rh.db.conn.maxActive: 200
dataplatform.rh.db.conn.maxIdle: 30
dataplatform.rh.db.conn.maxWait: 1000
dataplatform.rh.db.conn.autocommit: true
#最小空闲数
dataplatform.rh.db.conn.minIdle: 1
#初始化连接数,如果不设置,当容器启动后,会随着连接的数量逐个增加
dataplatform.rh.db.conn.initialSize: 1
#连接泄漏回收参数,是否自动回收超时连接
dataplatform.rh.db.conn.removeAbandoned: true
#连接泄漏回收参数,泄露的连接可以被删除的超时值,超时时间(以秒数为单位)
dataplatform.rh.db.conn.removeAbandonedTimeout: 180
#验证使用的SQL语句
dataplatform.rh.db.conn.validationQuery: SELECT 1
#指明连接是否被空闲连接回收器(如果有)进行检验,如果检测失败,则连接将被从池中去除
dataplatform.rh.db.conn.testWhileIdle: true
#借出连接时不要测试,否则很影响性能
dataplatform.rh.db.conn.testOnBorrow: false
#每30秒运行一次空闲连接回收器
dataplatform.rh.db.conn.timeBetweenEvictionRunsMillis: 30000
#在每次空闲连接回收器线程(如果有)运行时检查的连接数量
dataplatform.rh.db.conn.numTestsPerEvictionRun: 10

#cos
#COS.secretId: yourSecret
#COS.secretKey: your_secret_key
#COS.region: your_region
#COS.bucketName: your_bucket_name
#COS.url: your_url
#server
server.port: 8080

#token
jwtToken.timeout: 432000000
jwtToken.algorithm: HS512
jwtToken.secret: Pa@ss@Word
  
spring.servlet.multipart.enabled: true
spring.servlet.multipart.max-file-size: 20MB
spring.servlet.multipart.max-request-size: 200MB



